site_name: DolARK
nav:
    - Home: index.md
    - About: about.md

markdown_extensions:
  - markdown.extensions.admonition
  - pymdownx.arithmatex

extra_javascript:
  # other extra java script
  - mathjax-config.js
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
