site_name: DolARK
nav:
    - Home: index.md
    - About: about.md
    - Shocks: shocks.md
    - Equilibrium: equilibrium.md
    - Perturbation: perturbation.md
    - Krussell-Smith: krussell_smith.md

markdown_extensions:
  - markdown.extensions.admonition
  - pymdownx.arithmatex
  - pymdownx.superfences

extra_javascript:
  # other extra java script
  - mathjax-config.js
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
