# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.1

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/dolARK


    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install nose ipython
            pip install -r requirements.txt
            pip install -e .

      - run:
          name: run tests
          command: |
            python3 -m venv venv
            . venv/bin/activate
            nosetests dolark

      - add_ssh_keys:
          fingerprints:
            - "87:86:f1:57:00:16:bc:a4:d1:60:6b:e9:e2:88:d8:4d"

      - run:
          name: deploy doc
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install mkdocs
            pip install pymdown-extensions python-markdown-math
            if [ $(git symbolic-ref --short -q HEAD) == master ]; then mkdocs gh-deploy; fi
